### PR TITLE
Update node-forge package

### PR DESCRIPTION
**Pull request by allonsy**
Hey!
Great work on the package!
The dependency for the project: node-forge has a new version 0.6.33 which fixes some bugs that cause some functionality to crash, I've just updated your package.json to pull the updated version (the carrot tells npm to install the most up to date semantically compatible version of node-forge) so that any packages that rely upon yours (like googleapis) doesn't crash.

### CODE REVIEW

**Comment by allonsy** [comment]
@ryanseys what do you think of the changes?

**Comment by allonsy** [comment]
@ryanseys bump

**Comment by ryanseys** [comment]
Sorry about the delay! :) I released a new version 0.0.2 with these changes.

**Comment by allonsy** [comment]
no prob! keep up the great work!

**Pull request merged**
